### ISSUE TITLE
Ability to click on person on our team

### ISSUE THREAD

**Issue by adamdoe** [marketingincolor/mic-main-website#1]
@eddt , has this been looked at? Seems like a UX thing to me. Should the user be able to click directly on the team members photo to get to their page?

**Comment by eddt** [comment]
No, and we did so much customization with all these little components all over the site, that I don't really think much review/discussion took place in regards to the UX for such components. It is something we could certainly add to the 2 "team views", but I do find myself questioning the real NEED to do so.
